spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/rakustagram
        username: postgres
        password: postgres
        
server:
  port: 8082
